//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationLog
    {
        public int Id { get; set; }
        public System.DateTime LogDate { get; set; }
        public string Transaction { get; set; }
        public string SessionId { get; set; }
        public string ClientIpAddress { get; set; }
        public string ReturnCode { get; set; }
        public string ErrorCode { get; set; }
        public int UserId { get; set; }
    }
}
