//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BnnAppUser
    {
        public long Id { get; set; }
        public long StateId { get; set; }
        public string FbId { get; set; }
        public int Audience { get; set; }
        public int IsInterested { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string LastNames { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
        public string Extension { get; set; }
        public int ChildrenCount { get; set; }
        public int LocationCount { get; set; }
        public Nullable<System.DateTime> LockedAt { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaAviso { get; set; }
    }
}
