//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scorm
    {
        public int Id { get; set; }
        public string LessonLocation { get; set; }
        public string Credit { get; set; }
        public string ScoreRaw { get; set; }
        public string ScoreMin { get; set; }
        public string ScoreMax { get; set; }
        public string TotalTime { get; set; }
        public string SessionTime { get; set; }
        public string SuspendData { get; set; }
        public string LaunchData { get; set; }
        public string DataMasteryScore { get; set; }
        public string Entry { get; set; }
        public string Exit { get; set; }
        public string Version { get; set; }
    }
}
