//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCourse
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CourseId { get; set; }
        public string Status { get; set; }
        public int ScormId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Scorm Scorm { get; set; }
    }
}
