//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.IsAdmin = false;
            this.IsLogged = false;
            this.UserCourses = new HashSet<UserCourse>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SecondLastName { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsLogged { get; set; }
        public Nullable<System.DateTime> LastLogged { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Gender { get; set; }
        public short Ocupation { get; set; }
        public short Organization { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<UserCourse> UserCourses { get; set; }
    }
}
